export { default as ElPagination } from './pagination'
export { default as ElPage } from './page'
export { default as ElPageGroup } from './page-group'
export { default as ElPagePrev } from './page-prev'
export { default as ElPageNext } from './page-next'
