export { default as VkPaginationEl } from './pagination'
export { default as VkPaginationElPage } from './pagination--page'
export { default as VkPaginationElPageNext } from './pagination--page-next'
export { default as VkPaginationElPagePrev } from './pagination--page-prev'
export { default as VkPaginationElIconNext } from './pagination--icon-next'
export { default as VkPaginationElIconPrev } from './pagination--icon-prev'
