export { default as VkModalEl } from './modal'
export { default as VkModalElFull } from './modal-full'
export { default as VkModalElBody } from './modal--body'
export { default as VkModalElClose } from './modal--close'
export { default as VkModalElTitle } from './modal--title'
export { default as VkModalElDialog } from './modal--dialog'
export { default as VkModalElFooter } from './modal--footer'
export { default as VkModalElHeader } from './modal--header'
