export { default as Pagination } from './pagination'
export { default as PaginationPages } from './pagination--pages'
export { default as PaginationPageFirst } from './pagination--page-first'
export { default as PaginationPagePrev } from './pagination--page-prev'
export { default as PaginationPageNext } from './pagination--page-next'
export { default as PaginationPageLast } from './pagination--page-last'
