export { default as VkPagination } from './pagination'
export { default as VkPaginationPages } from './pagination--pages'
export { default as VkPaginationPageFirst } from './pagination--page-first'
export { default as VkPaginationPagePrev } from './pagination--page-prev'
export { default as VkPaginationPageNext } from './pagination--page-next'
export { default as VkPaginationPageLast } from './pagination--page-last'
