export { default as VkPagination } from './pagination'
export { default as VkPaginationPageFirst } from './page-first'
export { default as VkPaginationPagePrev } from './page-prev'
export { default as VkPaginationPageNext } from './page-next'
export { default as VkPaginationPageLast } from './page-last'
