export default [{
  name: 'Button',
  path: '/',
  component: require('./pages/Button')
}, {
  name: 'Modal',
  path: '/modal',
  component: require('./pages/Modal')
}, {
  name: 'Offcanvas',
  path: '/offcanvas',
  component: require('./pages/Offcanvas')
}, {
  name: 'Tabs',
  path: '/tabs',
  component: require('./pages/Tabs')
}, {
  name: 'Dropdown',
  path: '/dropdown',
  component: require('./pages/Dropdown')
}, {
  name: 'Tooltip',
  path: '/tooltip',
  component: require('./pages/Tooltip')
}, {
  name: 'Picker',
  path: '/picker',
  component: require('./pages/Picker')
}, {
  name: 'Datepicker',
  path: '/datepicker',
  component: require('./pages/Datepicker')
}, {
  name: 'Switcher',
  path: '/switcher',
  component: require('./pages/Switcher')
}, {
  name: 'Table',
  path: '/table',
  component: require('./pages/Table')
}, {
  name: 'Subnav',
  path: '/subnav',
  component: require('./pages/Subnav')
}, {
  name: 'Calendar',
  path: '/calendar',
  component: require('./pages/Calendar')
}, {
  name: 'Breadcrumb',
  path: '/breadcrumb',
  component: require('./pages/Breadcrumb')
}, {
  name: 'Pagination',
  path: '/pagination',
  component: require('./pages/Pagination')
}, {
  name: 'Upload',
  path: '/upload',
  component: require('./pages/Upload')
}]
